### PR TITLE
Fixed switching orientation bug

### LINKED ISSUE #1: Save Activitiy State when activity orientation is changed (bug?)
Just found out an interesting bug , so it seems that changing orientation of an app mid activity basically relaunches the entire activity like a restart activity or going to another activity screen and coming back to this after hitting the back button  .

What's also interesting is when this happens while your activity takes some data from an intentExtra pass , when the activity relaunches this received intent value will be null , making all sorts of bugs happen with the code

### PR DESCRIPTION
**Pull request by Govind-S-B**
Used `onSaveInstance` method for data persistence

### CODE REVIEW

File: app/src/main/java/com/example/rock_paper_scissor_app/Final.kt [hunk 1]
```diff
@@ -16,6 +16,11 @@ class Final : AppCompatActivity() {
     private lateinit var tryAgain : Button
     private lateinit var exit : Button
 
+    private var rounds : Int = 0
+    private var wonRounds : Int = 0
+    private var drawRounds : Int = 0
+    private var lostRounds : Int = 0
```
Comment (Govind-S-B) [inline app/src/main/java/com/example/rock_paper_scissor_app/Final.kt:22]: converted to global variables huh

**Review by Govind-S-B — COMMENTED** [review]
Yay looks good
